version: "3"

services:
  superset:
    image: apache/superset:2.1.0
    container_name: superset
    environment:
      - SUPERSET_CONFIG_PATH=/etc/superset/superset_config.py
    volumes:
      - ./superset_config.py:/etc/superset/superset_config.py
    ports:
      - "8088:8088"